=== Sandra-Gutierrez-Garcia/Sprint_2/S2.03/Ejercicio_2/schema-Óptica-proveedor.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "direccion",
    "especialidad",
    "id_proveedor",
    "NIF",
    "nombre",
    "telefono"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "direccion": {
      "type": "string"
    },
    "especialidad": {
      "type": "string"
    },
    "fax": {
      "type": "string"
    },
    "id_proveedor": {
      "type": "integer"
    },
    "NIF": {
      "type": "string"
    },
    "nombre": {
      "type": "string"
    },
    "telefono": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    }
  }
}

=== Sandra-Gutierrez-Garcia/Sprint_2/S2.03/Ejercicio_2/Documentos_dePreuba/Óptica.proveedor.json
[{
  "_id": {
    "$oid": "6810b94bc44aaaea9d156346"
  },
  "id_proveedor": 1,
  "nombre": "Óptica Visión Clara",
  "direccion": "Calle Lentes 10, 28001 Madrid",
  "telefono": "915554433",
  "NIF": "A12345678",
  "especialidad": "Gafas graduadas"
},
{
  "_id": {
    "$oid": "6810b94bc44aaaea9d156347"
  },
  "id_proveedor": 2,
  "nombre": "SunGlass España",
  "direccion": "Avenida del Sol 45, 08015 Barcelona",
  "telefono": "934445566",
  "fax": "934445567",
  "NIF": "B87654321",
  "especialidad": "Gafas de sol de diseño"
},
{
  "_id": {
    "$oid": "6810b94bc44aaaea9d156348"
  },
  "id_proveedor": 3,
  "nombre": "Cristales Ópticos Premium",
  "direccion": "Calle Microscopio 22, 46010 Valencia",
  "telefono": "961112233",
  "NIF": "V11223344",
  "especialidad": "Lentes de alta calidad"
},
{
  "_id": {
    "$oid": "6810b94bc44aaaea9d156349"
  },
  "id_proveedor": 4,
  "nombre": "Monturas Creativas",
  "direccion": "Paseo del Diseño 8, 48009 Bilbao",
  "telefono": "944556677",
  "fax": "944556678",
  "NIF": "C55667788",
  "especialidad": "Monturas innovadoras"
},
{
  "_id": {
    "$oid": "6810b94bc44aaaea9d15634a"
  },
  "id_proveedor": 5,
  "nombre": "Óptica Infantil",
  "direccion": "Plaza Pequeños 3, 41004 Sevilla",
  "telefono": "955667788",
  "NIF": "D99887766",
  "especialidad": "Gafas para niños"
}]
