=== Sandra-Gutierrez-Garcia/Sprint_2/S2.03/Ejercicio_2/schema-Óptica-ventas.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "fecha",
    "id_cliente",
    "id_empleado",
    "id_gafa",
    "id_venta",
    "tipo_de_pago"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "fecha": {
      "$ref": "#/$defs/Date"
    },
    "id_cliente": {
      "type": "integer"
    },
    "id_empleado": {
      "type": "integer"
    },
    "id_gafa": {
      "type": "integer"
    },
    "id_venta": {
      "type": "integer"
    },
    "tipo_de_pago": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    },
    "Date": {
      "type": "object",
      "properties": {
        "$date": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "$date"
      ],
      "additionalProperties": false
    }
  }
}

=== Sandra-Gutierrez-Garcia/Sprint_2/S2.03/Ejercicio_2/Documentos_dePreuba/Óptica.ventas.json
[{
  "_id": {
    "$oid": "68111503c44aaaea9d15636c"
  },
  "id_venta": 1,
  "fecha": {
    "$date": "2023-01-15T10:30:00.000Z"
  },
  "id_empleado": 2,
  "id_cliente": 3,
  "id_gafa": 1,
  "tipo_de_pago": "efectivo"
},
{
  "_id": {
    "$oid": "68111503c44aaaea9d15636d"
  },
  "id_venta": 2,
  "fecha": {
    "$date": "2023-01-16T14:45:00.000Z"
  },
  "id_empleado": 1,
  "id_cliente": 5,
  "id_gafa": 2,
  "tipo_de_pago": "tarjeta_credito"
},
{
  "_id": {
    "$oid": "68111503c44aaaea9d15636e"
  },
  "id_venta": 3,
  "fecha": {
    "$date": "2023-01-17T11:20:00.000Z"
  },
  "id_empleado": 4,
  "id_cliente": 2,
  "id_gafa": 3,
  "tipo_de_pago": "efectivo"
}]
