=== Sandra-Gutierrez-Garcia/Sprint_2/S2.03/Ejercicio_2/schema-Óptica-empleado.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "apellido",
    "correo_electronico",
    "fecha_de_entrada",
    "id_empleado",
    "nombre",
    "telefono"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "apellido": {
      "type": "string"
    },
    "correo_electronico": {
      "type": "string"
    },
    "fecha_de_entrada": {
      "$ref": "#/$defs/Date"
    },
    "id_empleado": {
      "type": "integer"
    },
    "nombre": {
      "type": "string"
    },
    "telefono": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    },
    "Date": {
      "type": "object",
      "properties": {
        "$date": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "$date"
      ],
      "additionalProperties": false
    }
  }
}

=== Sandra-Gutierrez-Garcia/Sprint_2/S2.03/Ejercicio_2/Documentos_dePreuba/Óptica.empleado.json
[{
  "_id": {
    "$oid": "6811144ec44aaaea9d156366"
  },
  "id_empleado": 1,
  "nombre": "María",
  "apellido": "González",
  "telefono": "+34 612345678",
  "fecha_de_entrada": {
    "$date": "2020-05-15T00:00:00.000Z"
  },
  "correo_electronico": "maria.gonzalez@empresa.com"
},
{
  "_id": {
    "$oid": "6811144ec44aaaea9d156367"
  },
  "id_empleado": 2,
  "nombre": "Carlos",
  "apellido": "Martínez",
  "telefono": "+34 687654321",
  "fecha_de_entrada": {
    "$date": "2019-11-22T00:00:00.000Z"
  },
  "correo_electronico": "carlos.martinez@empresa.com"
},
{
  "_id": {
    "$oid": "6811144ec44aaaea9d156368"
  },
  "id_empleado": 3,
  "nombre": "Ana",
  "apellido": "Rodríguez",
  "telefono": "+34 699112233",
  "fecha_de_entrada": {
    "$date": "2021-02-10T00:00:00.000Z"
  },
  "correo_electronico": "ana.rodriguez@empresa.com"
},
{
  "_id": {
    "$oid": "6811144ec44aaaea9d156369"
  },
  "id_empleado": 4,
  "nombre": "Javier",
  "apellido": "López",
  "telefono": "+34 655443322",
  "fecha_de_entrada": {
    "$date": "2018-07-30T00:00:00.000Z"
  },
  "correo_electronico": "javier.lopez@empresa.com"
},
{
  "_id": {
    "$oid": "6811144ec44aaaea9d15636a"
  },
  "id_empleado": 5,
  "nombre": "Sofía",
  "apellido": "Hernández",
  "telefono": "+34 677889900",
  "fecha_de_entrada": {
    "$date": "2022-01-05T00:00:00.000Z"
  },
  "correo_electronico": "sofia.hernandez@empresa.com"
}]
